version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    docker:
      - image: circleci/node:current

commands:
  install-dependencies:
    steps:
      - run: npm install
  cache-dependencies:
    steps:
      - save_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

jobs:
  build:
    executor: default
    steps:
      - checkout
      - install-dependencies
      - cache-dependencies

workflows:
  version: 2
  ci-master:
    jobs:
      - build:
          context: aws-account
